-- MySQL Script generated by MySQL Workbench
-- Fri Dec 15 22:45:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cabinet_veterinar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cabinet_veterinar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cabinet_veterinar` DEFAULT CHARACTER SET utf8 ;
USE `cabinet_veterinar` ;

-- -----------------------------------------------------
-- Table `cabinet_veterinar`.`Proprietar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cabinet_veterinar`.`Proprietar` (
  `idProprietar` INT NULL,
  `nume` VARCHAR(45) NOT NULL,
  `prenume` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `nr_tel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProprietar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cabinet_veterinar`.`Pacient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cabinet_veterinar`.`Pacient` (
  `idPacient` INT NULL,
  `nume` VARCHAR(45) NOT NULL,
  `specie` VARCHAR(45) NOT NULL,
  `rasa` VARCHAR(45) NOT NULL,
  `gen` VARCHAR(45) NOT NULL,
  `data_nasterii` DATE NOT NULL,
  `Proprietar_idProprietar` INT NULL,
  PRIMARY KEY (`idPacient`, `Proprietar_idProprietar`),
  INDEX `fk_Pacient_Proprietar_idx` (`Proprietar_idProprietar` ASC) VISIBLE,
  CONSTRAINT `fk_Pacient_Proprietar`
    FOREIGN KEY (`Proprietar_idProprietar`)
    REFERENCES `cabinet_veterinar`.`Proprietar` (`idProprietar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cabinet_veterinar`.`Consultatie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cabinet_veterinar`.`Consultatie` (
  `idConsultatie` INT NULL,
  `data_consultatie` DATETIME NOT NULL,
  `motiv` VARCHAR(45) NOT NULL,
  `observatii` MEDIUMTEXT NOT NULL,
  `Pacient_idPacient` INT NULL,
  `Pacient_Proprietar_idProprietar` INT NULL,
  PRIMARY KEY (`idConsultatie`, `Pacient_idPacient`, `Pacient_Proprietar_idProprietar`),
  INDEX `fk_Consultatie_Pacient1_idx` (`Pacient_idPacient` ASC, `Pacient_Proprietar_idProprietar` ASC) VISIBLE,
  CONSTRAINT `fk_Consultatie_Pacient1`
    FOREIGN KEY (`Pacient_idPacient` , `Pacient_Proprietar_idProprietar`)
    REFERENCES `cabinet_veterinar`.`Pacient` (`idPacient` , `Proprietar_idProprietar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cabinet_veterinar`.`Tratament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cabinet_veterinar`.`Tratament` (
  `idTratament` INT NULL,
  `data_tratament` DATETIME NOT NULL,
  `descriere_tratament` MEDIUMTEXT NOT NULL,
  `dozaj` VARCHAR(45) NOT NULL,
  `durata` INT NOT NULL,
  `Consultatie_idConsultatie` INT NULL,
  `Consultatie_Pacient_idPacient` INT NULL,
  `Consultatie_Pacient_Proprietar_idProprietar` INT NULL,
  PRIMARY KEY (`idTratament`, `Consultatie_idConsultatie`, `Consultatie_Pacient_idPacient`, `Consultatie_Pacient_Proprietar_idProprietar`),
  INDEX `fk_Tratament_Consultatie1_idx` (`Consultatie_idConsultatie` ASC, `Consultatie_Pacient_idPacient` ASC, `Consultatie_Pacient_Proprietar_idProprietar` ASC) VISIBLE,
  CONSTRAINT `fk_Tratament_Consultatie1`
    FOREIGN KEY (`Consultatie_idConsultatie` , `Consultatie_Pacient_idPacient` , `Consultatie_Pacient_Proprietar_idProprietar`)
    REFERENCES `cabinet_veterinar`.`Consultatie` (`idConsultatie` , `Pacient_idPacient` , `Pacient_Proprietar_idProprietar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
